### ISSUE TITLE
Locate the ppr index corresponding to the closest value

### ISSUE THREAD

**Issue by betiniakarandut** [betiniakarandut/portfolio-project#7]
Remember the `pivot_sciv()` returns the pivot sciv. Locate the index of the coreesponding pseudoreduced pressure at above and below.
Use the intersection of Ppr and Tpr to read the sciv(sukkar and cornell value).

**Comment by PedramHaeri** [comment]
Hi I would like to try and fix this issue. could you please assign it to me?

**Comment by betiniakarandut** [comment]
Hey thank you much for your reaching out to help 👍  . I later resolved the issue last night.
